services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=find_a_job'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  phpmyadmin:
    image: 'phpmyadmin'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8081:80